#################################
#           Fading              #
#################################
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5;

#################################
#           Corners             #
#################################
corner-radius = 12;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'dwm'",
  "class_g = 'dwmbar'"
];

#################################
#             Blur              #
#################################
# Dual-kawase is best for the "frosted glass" look
blur-method = "dual_kawase";
blur-strength = 8;
blur-background = true;
blur-background-fixed = true;

blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'dwm'",
  "class_g = 'dwmbar'",
  "_GTK_FRAME_EXTENTS@:c"
];

#################################
#           Opacity             #
#################################
inactive-opacity = 0.80;
frame-opacity = 1.0;
inactive-opacity-override = false;

# This rule syncs with your qutebrowser #RRGGBBAA settings
opacity-rule = [
  "95:class_g = 'qutebrowser' && focused",
  "85:class_g = 'qutebrowser' && !focused"
];

focus-exclude = [ 
  "class_g = 'Cairo-clock'",
  "window_type = 'dock'" 
];

#################################
#       General Settings        #
#################################
backend = "glx";
vsync = true;
mark-wmwin-focused = true;
mark-ovlptr-focused = true;
detect-rounded-corners = true;
detect-client-opacity = true;

# Set to false to fix flickering/ghosting in browsers
use-damage = false;

wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; };
  dock = { shadow = false; clip-shadow-above = true; blur-background = false; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 0.8; }
  dropdown_menu = { opacity = 0.8; }
};


animations = true;

animation-for-open-window = "zoom";
animation-for-unmap-window = "zoom";

animation-stiffness = 250;
animation-dampening = 20;
animation-mass = 0.8;

animation-clamping = false;
