#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

alias v='vim'
alias c='clear'
alias ps='poweroff'
alias pr='reboot'
alias fetch='neofetch'
alias ap='sudo pacman -S'
alias ay='yay -S'
alias z='zsh'


